"""Interactive setup wizard — scaffolds scorers, fixtures, and config for new projects.

Usage:
    python -m llm_bench init
    llm-bench init
    llm-bench init --from config.yaml
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from llm_bench.configs import ALL_CONFIGS

_SCORER_TEMPLATE = '''\
"""Quality scorer for the '{task_name}' task.

Implement your scoring logic in the score() method.
Return a dict with 'score' (float 0-1) and any sub_scores you want to track.
"""

from llm_bench import Fixture


class {class_name}:
    """Scores LLM responses for the '{task_name}' task."""

    def score(self, response: str, fixture: Fixture, **kwargs) -> dict:
        # TODO: Implement your scoring logic here.
        #
        # Examples of quality checks:
        #   - Does the response contain required fields/structure?
        #   - Does it pass validation?
        #   - Is the output correct (compared to expected)?
        #   - Is it concise/relevant?
        #
        # Return format:
        #   {{"score": 0.0-1.0, "sub_score_name": 0.0-1.0, ...}}

        return {{"score": 0.0}}  # Replace with real scoring logic
'''

_FIXTURE_TEMPLATE = '''\
"""Test fixtures for the '{task_name}' task.

Each fixture is a golden test case: a (system_prompt, user_prompt) pair
that exercises a representative scenario for this task.
"""

from llm_bench import SimpleFixture


def get_fixtures() -> list[SimpleFixture]:
    """Return test fixtures for benchmarking."""
    return [
        SimpleFixture(
            fixture_id="{task_name}_example_1",
            system_prompt="You are a helpful assistant.",
            user_prompt="TODO: Add a representative prompt for the {task_name} task.",
        ),
        # Add more fixtures for broader coverage:
        # SimpleFixture(
        #     fixture_id="{task_name}_example_2",
        #     system_prompt="...",
        #     user_prompt="...",
        # ),
    ]
'''

_CONFIG_TEMPLATE = '''\
"""llm-bench configuration — generated by `llm-bench init`."""

import os
from llm_bench import Client, TaskDefinition, BenchmarkRunner, AutoSelector, SQLiteStorage
{scorer_imports}
{fixture_imports}

# --- OpenRouter API Key ---
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
if not OPENROUTER_API_KEY:
    raise ValueError("Set OPENROUTER_API_KEY environment variable")

# --- Client ---
client = Client(api_key=OPENROUTER_API_KEY)

# --- Storage ---
storage = SQLiteStorage()  # Stores results in ~/.llm-bench/benchmarks.db

# --- Tasks ---
tasks = [
{task_definitions}]

# --- Runner ---
runner = BenchmarkRunner(client=client, tasks=tasks, storage=storage)

# --- Auto-Selector ---
selector = AutoSelector(storage=storage, tasks=tasks)
'''

_RUN_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
"""Run benchmarks and print recommendations."""

from llm_bench_config import runner, selector
from llm_bench import analyze

# Run benchmarks (1 run per model/fixture combo)
print("Running benchmarks...")
results = runner.run_all(n_runs=1)
print(f"Completed {{len(results)}} benchmark runs")

# Get recommendations
recs = selector.refresh()
print("\\nRecommendations:")
for task, config in recs.items():
    print(f"  {{task}}: {{config}}")

# Print detailed tables
stats = selector.get_stats()
for task_name, configs in stats.items():
    print(analyze.format_table(task_name, configs))
'''

_ENV_TEMPLATE = """\
# llm-bench configuration
# Get your OpenRouter API key at https://openrouter.ai/keys
OPENROUTER_API_KEY=sk-or-v1-your-key-here

# Optional: Add BYOK keys in your OpenRouter account settings
# for Anthropic, Google, Mistral, etc. to get direct pricing.
# https://openrouter.ai/settings/integrations
"""


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    result = input(f"{prompt}{suffix}: ").strip()
    return result or default


def _ask_yn(prompt: str, default: bool = True) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    result = input(f"{prompt}{suffix}: ").strip().lower()
    if not result:
        return default
    return result in ("y", "yes")


def _to_class_name(task_name: str) -> str:
    return "".join(word.capitalize() for word in task_name.replace("-", "_").split("_")) + "Scorer"


def run_wizard(output_dir: str | None = None) -> None:
    """Run the interactive setup wizard."""
    print("\n  llm-bench Setup Wizard")
    print("  " + "=" * 40)
    print()

    # 1. Project name
    project_name = _ask("Project name", "my-project")

    # 2. Tasks
    print("\nDefine your LLM tasks (e.g., summarize, classify, generate_code).")
    print("These are the distinct types of LLM calls you want to benchmark.\n")

    tasks: list[dict] = []
    while True:
        task_name = _ask(f"Task name (or empty to finish)", "").strip()
        if not task_name:
            if not tasks:
                print("  You need at least one task.")
                continue
            break

        task_name = task_name.lower().replace(" ", "_").replace("-", "_")
        desc = _ask(f"  Description for '{task_name}'", f"Benchmark for {task_name}")
        floor = _ask(f"  Quality floor (0.0-1.0)", "0.5")
        try:
            floor_val = float(floor)
        except ValueError:
            floor_val = 0.5

        tasks.append({"name": task_name, "description": desc, "floor": floor_val})
        print(f"  Added task: {task_name} (floor={floor_val})")
        print()

    # 3. Models
    print(f"\nBuilt-in models ({len(ALL_CONFIGS)} available):")
    for i, c in enumerate(ALL_CONFIGS):
        print(f"  {c.name}")
    print()

    use_all = _ask_yn("Benchmark all built-in models?", True)
    selected_models = None
    if not use_all:
        model_input = _ask("Enter model names (comma-separated)")
        selected_models = [m.strip() for m in model_input.split(",") if m.strip()]

    # 4. Dashboard
    include_dashboard = _ask_yn("Include web dashboard?", True)

    # 5. Generate files
    out_dir = Path(output_dir) if output_dir else Path.cwd()
    scorers_dir = out_dir / "scorers"
    fixtures_dir = out_dir / "fixtures"
    scorers_dir.mkdir(parents=True, exist_ok=True)
    fixtures_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nGenerating files in {out_dir}...")

    # Generate scorer files
    scorer_imports = []
    fixture_imports = []
    task_defs = []
    for task in tasks:
        name = task["name"]
        class_name = _to_class_name(name)

        # Scorer
        scorer_path = scorers_dir / f"{name}.py"
        scorer_path.write_text(_SCORER_TEMPLATE.format(task_name=name, class_name=class_name))
        print(f"  Created {scorer_path}")

        # Fixtures
        fixture_path = fixtures_dir / f"{name}.py"
        fixture_path.write_text(_FIXTURE_TEMPLATE.format(task_name=name))
        print(f"  Created {fixture_path}")

        scorer_imports.append(f"from scorers.{name} import {class_name}")
        fixture_imports.append(f"from fixtures.{name} import get_fixtures as get_{name}_fixtures")

        models_arg = ""
        if selected_models:
            models_arg = f", models={selected_models!r}"

        task_defs.append(
            f"    TaskDefinition(\n"
            f"        name=\"{name}\",\n"
            f"        scorer={class_name}(),\n"
            f"        fixtures=get_{name}_fixtures(),\n"
            f"        quality_floor={task['floor']}{models_arg},\n"
            f"    ),"
        )

    # Init files for scorers and fixtures
    (scorers_dir / "__init__.py").touch()
    (fixtures_dir / "__init__.py").touch()

    # Config file
    config_path = out_dir / "llm_bench_config.py"
    config_path.write_text(_CONFIG_TEMPLATE.format(
        scorer_imports="\n".join(scorer_imports),
        fixture_imports="\n".join(fixture_imports),
        task_definitions="\n".join(task_defs),
    ))
    print(f"  Created {config_path}")

    # Run script
    run_path = out_dir / "run_benchmarks.py"
    run_path.write_text(_RUN_SCRIPT_TEMPLATE)
    print(f"  Created {run_path}")

    # .env.example
    env_path = out_dir / ".env.example"
    env_path.write_text(_ENV_TEMPLATE)
    print(f"  Created {env_path}")

    print(f"\nDone! Next steps:")
    print(f"  1. Set your OPENROUTER_API_KEY: export OPENROUTER_API_KEY=sk-or-v1-...")
    print(f"  2. Add BYOK keys at https://openrouter.ai/settings/integrations")
    print(f"  3. Implement your scorers in scorers/")
    print(f"  4. Add test fixtures in fixtures/")
    print(f"  5. Run: python run_benchmarks.py")
    if include_dashboard:
        print(f"  6. View dashboard: llm-bench dashboard")
    print()


def run_from_config(config_path: str) -> None:
    """Generate scaffold from a YAML/TOML config file (non-interactive)."""
    path = Path(config_path)
    if not path.exists():
        print(f"Error: Config file not found: {config_path}")
        sys.exit(1)

    import json

    if path.suffix in (".yaml", ".yml"):
        try:
            import yaml
            config = yaml.safe_load(path.read_text())
        except ImportError:
            print("Error: PyYAML required for YAML config. Install with: pip install pyyaml")
            sys.exit(1)
    elif path.suffix == ".toml":
        try:
            import tomllib
        except ImportError:
            import tomli as tomllib
        config = tomllib.loads(path.read_text())
    elif path.suffix == ".json":
        config = json.loads(path.read_text())
    else:
        print(f"Error: Unsupported config format: {path.suffix}")
        sys.exit(1)

    # Extract config and generate files
    tasks = config.get("tasks", [])
    if not tasks:
        print("Error: No tasks defined in config file")
        sys.exit(1)

    output_dir = config.get("output_dir", ".")
    out_dir = Path(output_dir)
    scorers_dir = out_dir / "scorers"
    fixtures_dir = out_dir / "fixtures"
    scorers_dir.mkdir(parents=True, exist_ok=True)
    fixtures_dir.mkdir(parents=True, exist_ok=True)

    scorer_imports = []
    fixture_imports = []
    task_defs = []

    for task in tasks:
        name = task["name"]
        class_name = _to_class_name(name)
        floor = task.get("quality_floor", 0.5)
        models = task.get("models")

        (scorers_dir / f"{name}.py").write_text(
            _SCORER_TEMPLATE.format(task_name=name, class_name=class_name)
        )
        (fixtures_dir / f"{name}.py").write_text(
            _FIXTURE_TEMPLATE.format(task_name=name)
        )

        scorer_imports.append(f"from scorers.{name} import {class_name}")
        fixture_imports.append(f"from fixtures.{name} import get_fixtures as get_{name}_fixtures")

        models_arg = f", models={models!r}" if models else ""
        task_defs.append(
            f"    TaskDefinition(\n"
            f"        name=\"{name}\",\n"
            f"        scorer={class_name}(),\n"
            f"        fixtures=get_{name}_fixtures(),\n"
            f"        quality_floor={floor}{models_arg},\n"
            f"    ),"
        )

    (scorers_dir / "__init__.py").touch()
    (fixtures_dir / "__init__.py").touch()

    (out_dir / "llm_bench_config.py").write_text(_CONFIG_TEMPLATE.format(
        scorer_imports="\n".join(scorer_imports),
        fixture_imports="\n".join(fixture_imports),
        task_definitions="\n".join(task_defs),
    ))
    (out_dir / "run_benchmarks.py").write_text(_RUN_SCRIPT_TEMPLATE)
    (out_dir / ".env.example").write_text(_ENV_TEMPLATE)

    print(f"Generated scaffold in {out_dir} from {config_path}")
